{% set name = "sagemaker-mlflow" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker_mlflow-{{ version }}.tar.gz
  sha256: 6786b9aa738bf0ec551dc99bd44069ac39ad202fa234f99b2fc914556f1af2f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - mlflow-skinny >=2.8
    - python >={{ python_min }}
    - boto3 >=1.34
    - mlflow >=2.8

test:
  imports:
    - sagemaker_mlflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/sagemaker-mlflow
  summary: AWS Plugin for MLFlow with SageMaker
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - claytonparnell
    - saimidu
